<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows7.0</TargetFramework>
    <Nullable>disable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>gtwave.ico</ApplicationIcon>
    <OutputPath>C:\GTWave\bin\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <BaseOutputPath>C:\GTWave\bin</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="gtwave.ico" />
    <Compile Include="..\GTFinder_Shared\**\*.cs" LinkBase="Shared" />
    <EmbeddedResource Include="..\GTFinder_Shared\**\*.resx" LinkBase="Shared" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PacketDotNet" Version="0.13.0" />
    <PackageReference Include="SharpPcap" Version="4.2.0" />
    <PackageReference Include="System.Management" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>